name: CI
on: pull_request
env:
  CI: true
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build --filter="./packages/*"
      # TODO: use turborepo to cache and speed up?
      - name: check
        run: pnpm ci
